### PR TITLE
[FIX] properly escape dropped text

### PR DESCRIPTION
**Pull request by Zinston**

### CODE REVIEW

**Comment by dmo-odoo** [comment]
cc @mart-e The proposed fix for `_onDrop`. Seems fine to me.

**Review by mart-e — COMMENTED** [review]
LGTM  :+1:  cc @xmo-odoo

**Comment by xmo-odoo** [comment]
Seems fine, though does it no need to fix up the newline things? Not sure what the expectation is when dropping / pasting multiline text, but the original did mess around with that, and `_insert` seems to have no provisions related to newlines.

**Comment by Zinston** [comment]
Testing it manually I noticed the newlines created <br>s out of the box. I think the replace was an artifact of an earlier implementation.

**Pull request merged**
